# source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
require_relative '../node_modules/react-native/scripts/react_native_pods'


require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'
inhibit_all_warnings!

install! 'cocoapods', :deterministic_uuids => false

# def add_flipper_pods!(versions = {})
#   versions['Flipper'] ||= '~> 0.33.1'
#   versions['DoublpeConversion'] ||= '1.1.7'
#   versions['Flipper-Folly'] ||= '~> 2.1'
#   versions['Flipper-Glog'] ||= '0.3.6'
#   versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
#   versions['Flipper-RSocket'] ||= '~> 1.0'

#   pod 'FlipperKit', versions['Flipper'], :configuration => 'Debug'
#   pod 'FlipperKit/FlipperKitLayoutPlugin', versions['Flipper'], :configuration => 'Debug'
#   pod 'FlipperKit/SKIOSNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
#   pod 'FlipperKit/FlipperKitUserDefaultsPlugin', versions['Flipper'], :configuration => 'Debug'
#   pod 'FlipperKit/FlipperKitReactPlugin', versions['Flipper'], :configuration => 'Debug'

#   # List all transitive dependencies for FlipperKit pods
#   # to avoid them being linked in Release builds
#   pod 'Flipper', versions['Flipper'], :configuration => 'Debug'
#   pod 'Flipper-DoubleConversion', versions['DoubleConversion'], :configuration => 'Debug'
#   pod 'Flipper-Folly', versions['Flipper-Folly'], :configuration => 'Debug'
#   pod 'Flipper-Glog', versions['Flipper-Glog'], :configuration => 'Debug'
#   pod 'Flipper-PeerTalk', versions['Flipper-PeerTalk'], :configuration => 'Debug'
#   pod 'Flipper-RSocket', versions['Flipper-RSocket'], :configuration => 'Debug'
#   pod 'FlipperKit/Core', versions['Flipper'], :configuration => 'Debug'
#   pod 'FlipperKit/CppBridge', versions['Flipper'], :configuration => 'Debug'
#   pod 'FlipperKit/FBCxxFollyDynamicConvert', versions['Flipper'], :configuration => 'Debug'
#   pod 'FlipperKit/FBDefines', versions['Flipper'], :configuration => 'Debug'
#   pod 'FlipperKit/FKPortForwarding', versions['Flipper'], :configuration => 'Debug'
#   pod 'FlipperKit/FlipperKitHighlightOverlay', versions['Flipper'], :configuration => 'Debug'
#   pod 'FlipperKit/FlipperKitLayoutTextSearchable', versions['Flipper'], :configuration => 'Debug'
#   pod 'FlipperKit/FlipperKitNetworkPlugin', versions['Flipper'], :configuration => 'Debug'

#   # http://xingyun.xiaojukeji.com/docs/dokit/#/iosGuide
#     pod 'DoraemonKit/Core', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #必选
#     pod 'DoraemonKit/WithLogger', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
#     # pod 'DoraemonKit/WithGPS', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
#     # pod 'DoraemonKit/WithLoad', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
#     # pod 'DoraemonKit/WithDatabase', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
#     # pod 'DoraemonKit/WithMLeaksFinder', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
#     # pod 'DoraemonKit/WithWeex', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
# end

# # Post Install processing for Flipper
# def flipper_post_install(installer)
#   installer.pods_project.targets.each do |target|
#     if target.name == 'YogaKit'
#       target.build_configurations.each do |config|
#         config.build_settings['SWIFT_VERSION'] = '4.1'
#       end
#     end
#   end
# end

target 'wanya_native' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'UMCCommon', '~> 2.1.4'
  pod 'UMCAnalytics'
  pod 'UMCPush'
  pod 'UMCSecurityPlugins'

  # pod 'DoraemonKit/Core', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #必选
  # pod 'DoraemonKit/WithLogger', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
  # pod 'DoraemonKit/WithGPS', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
  # pod 'DoraemonKit/WithLoad', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
  # pod 'DoraemonKit/WithDatabase', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
  # pod 'DoraemonKit/WithMLeaksFinder', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选
  # pod 'DoraemonKit/WithWeex', :git => "https://gitee.com/yixiangboy/DoraemonKit.git", :tag => '3.0.2', :configurations => ['Debug'] #可选

  permissions_path = '../node_modules/react-native-permissions/ios'

  # pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency.podspec"
  # pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral.podspec"
  # pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars.podspec"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  # pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  # pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID.podspec"
  # pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  # pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  # pod 'Permission-Motion', :path => "#{permissions_path}/Motion.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  # pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders.podspec"
  # pod 'Permission-Siri', :path => "#{permissions_path}/Siri.podspec"
  # pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition.podspec"
  # pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit.podspec"

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'wanya_nativeTests' do
    inherit! :complete
    # Pods for testing
  end

  # use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'wanya_native-tvOS' do
  # Pods for wanya_native-tvOS

  target 'wanya_native-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
