# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    sigh(adhoc: true, skip_certificate_verification: true)
    gym(
        scheme: "wanya_native",
        export_method: "ad-hoc",
        clean: true,
        output_directory: "./build"
       )

    # upload_to_testflight
  end
end
