# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    sigh(adhoc: true, team_id: "K7KF6RDWDW", username: 'tianlu1677@gmail.com')
    gym(
        scheme: "wanya_native",
        include_bitcode: false,
        export_options: {
          uploadBitcode: false,
          uploadSymbol: true,
          compileBitcode: false,
          method: "ad-hoc",
        },
        output_directory: "./build",        
       )
    fir_cli api_token: "f684f86f55c235e73a1dbe75a7ce365d",  changelog: "APP"
    # upload_to_testflight
  end

  lane :deploy do
    token = "f684f86f55c235e73a1dbe75a7ce365d"
    ipa_path = "#{Dir.pwd.gsub('fastlane', '')}build/顽鸦.ipa"
    puts "url => #{ipa_path}"
    fir_cli api_token: token, specify_file_path: ipa_path
  end
end
