import PlayScoreNode from './PlayScore';
import AvatorNode from './Avator';
import JoinAccountsNode from './JoinAccounts';
import SearchNode from './Search';
import BadgeMessageNode from './BadgeMessage';
import {JoinBtn} from './Button';
import CityListNode from './CityList';
import JoinActivityNode from './JoinActivity';
import GoBackNode from './GoBack';
import CustomizeHeaderNode from './CustomizeHeader';
import {Loading} from './Modal';
import BottomModalNode from './BottomModal';
import BlurViewNode from './BlurViewComponent';
import CategoryDrawerNode from './CategoryDrawer';
import RecommendSearchNode from './RecommendSearch';
import SelectListHeaderNode from './SelectListHeader';
import TopBackNode from './TopBack';

export const PlayScore = PlayScoreNode;
export const Avator = AvatorNode;
export const JoinAccounts = JoinAccountsNode;
export const Search = SearchNode;
export const BadgeMessage = BadgeMessageNode;
export const JoinButton = JoinBtn;
export const CityList = CityListNode;
export const ModalLoading = Loading;
export const JoinActivity = JoinActivityNode;
export const GoBack = GoBackNode;
export const CustomizeHeader = CustomizeHeaderNode;
export const BottomModal = BottomModalNode;
export const BlurView = BlurViewNode;
export const CategoryDrawer = CategoryDrawerNode;
export const RecommendSearch = RecommendSearchNode;
export const SelectListHeader = SelectListHeaderNode;
export const TopBack = TopBackNode;
export {default as ModalInfo} from './ModalInfo';
